from enum import StrEnum


class TaskPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"


class TaskStatus(StrEnum):
    NEW = "NEW"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_AUTHOR = "WAITING_AUTHOR"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RecurrenceUnit(StrEnum):
    DAYS = "DAYS"
    WEEKS = "WEEKS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"


class TaskEventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_UNABLE = "TASK_UNABLE"
    TASK_RESOLVED = "TASK_RESOLVED"
    TITLE_CHANGED = "TITLE_CHANGED"
    DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    ASSIGNEES_CHANGED = "ASSIGNEES_CHANGED"
    DEADLINE_CHANGED = "DEADLINE_CHANGED"
    RECURRENCE_CHANGED = "RECURRENCE_CHANGED"
    RECURRENCE_INSTANCE_CREATED = "RECURRENCE_INSTANCE_CREATED"
    ASSIGNEE_LEFT_CHAT = "ASSIGNEE_LEFT_CHAT"


class NotificationType(StrEnum):
    BEFORE_7_DAYS = "BEFORE_7_DAYS"
    BEFORE_3_DAYS = "BEFORE_3_DAYS"
    BEFORE_1_DAY = "BEFORE_1_DAY"
    DUE_DAY = "DUE_DAY"
    BEFORE_3_HOURS = "BEFORE_3_HOURS"
    AT_DEADLINE = "AT_DEADLINE"
    URGENT = "URGENT"
    OVERDUE = "OVERDUE"
    DAILY_SUMMARY = "DAILY_SUMMARY"


class NotificationStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    CANCELLED = "CANCELLED"


class DeliveryStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    RETRY = "RETRY"
    UNAVAILABLE = "UNAVAILABLE"
